# 发件人邮件服务器相关配置
spring.mail.host=smtp.qq.com
spring.mail.port=465
# 配置个人QQ账户和密码(密码是加密后的授权码)
spring.mail.username=your_email@qq.com
spring.mail.password=your_authorization_code
spring.mail.default-encoding=UTF-8
# 邮件服务超时时间配置
spring.mail.properties.mail.smtp.connectiontimeout=35000
spring.mail.properties.mail.smtp.timeout=33000
spring.mail.properties.mail.smtp.writetimeout=35000
spring.mail.properties.mail.smtp.readtimeout=35000
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
